import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    nav_home: 'Ana Sayfa',
    nav_features: 'Özellikler',
    nav_pricing: 'Fiyatlandırma',
    nav_references: 'Referanslar',
    nav_success_stories: 'Başarı Hikayeleri',
    nav_about: 'Hakkımızda',
    nav_why_us: 'Neden Biz?',
    nav_contact: 'İletişim',
    nav_cta: 'Hemen Başla',

    hero_title: 'İnsan Kaynaklarını Yapay Zeka ile Yönetin',
    hero_subtitle: 'Devamsızlık takibi, izin yönetimi ve işe alım süreçlerinizi tamamen otomatikleştirin. Telegram üzerinden çalışan, kurulumu 5 dakika süren AI asistanınız.',
    hero_cta_primary: 'Ücretsiz Demo İsteyin',
    hero_cta_secondary: 'WhatsApp Destek',

    trust_1: '5 Dakikada Kurulum',
    trust_2: '100% Otomatik',
    trust_3: 'Telegram Tabanlı',
    trust_4: 'AI Destekli',

    stat_1_value: '1,000+',
    stat_1_label: 'Mutlu İşletme',
    stat_2_value: '50,000+',
    stat_2_label: 'Çalışan Takibi',
    stat_3_value: '%95',
    stat_3_label: 'Zaman Tasarrufu',
    stat_4_value: '24/7',
    stat_4_label: 'Otomatik Sistem',

    features_title: 'Özellikler',

    feature_1_title: 'Lokasyon Bazlı Akıllı Devamsızlık Takibi',
    feature_1_desc: 'Çalışanlarınız Telegram üzerinden lokasyon paylaşarak giriş-çıkış yapar. AI asistan otomatik devamsızlık kontrolü, geç kalma bildirimleri ve günlük raporlar sunar.',
    feature_1_bullet_1: 'Gerçek zamanlı lokasyon doğrulama',
    feature_1_bullet_2: 'Otomatik giriş-çıkış kayıtları',
    feature_1_bullet_3: 'Günlük/aylık otomatik raporlar',
    feature_1_bullet_4: 'Geç kalma bildirimleri yöneticilere',
    feature_1_bullet_5: 'Maaş hesaplama entegrasyonu',

    feature_2_title: 'Yapay Zeka Destekli Otomatik İzin Onayı',
    feature_2_desc: 'Çalışanlar Telegram\'dan doğal dille izin talep eder. AI asistan hastalık izinlerini otomatik onaylar, diğer talepleri yöneticiye yönlendirir.',
    feature_2_bullet_1: 'Doğal dil işleme ile izin talebi',
    feature_2_bullet_2: 'Tek günlük hastalık izni otomatik onay',
    feature_2_bullet_3: 'Yönetici onay sistemi',
    feature_2_bullet_4: 'Kalan izin hesaplama',
    feature_2_bullet_5: 'İzin geçmişi raporları',

    feature_3_title: 'Otomatik CV İşleme ve Aday Değerlendirme',
    feature_3_desc: 'Pozisyonunuz için gelen tüm CV\'ler AI tarafından analiz edilir, puanlanır ve en uygun adaylar belirlenir. Mülakat sorularını AI oluşturur.',
    feature_3_bullet_1: 'Otomatik CV parsing ve puanlama',
    feature_3_bullet_2: 'Aday sıralama algoritması',
    feature_3_bullet_3: 'AI mülakat soruları',
    feature_3_bullet_4: 'Otomatik görüşme planlama',
    feature_3_bullet_5: 'Aday iletişim yönetimi',

    feature_4_title: 'İşletmenize Özel AI Otomasyonları',
    feature_4_desc: 'İhtiyaçlarınıza göre özelleştirilebilir otomasyon sistemleri. Sözleşme yönetimi, eğitim takibi, bildirim sistemleri ve daha fazlası.',
    feature_4_bullet_1: 'Otomatik sözleşme imzalama',
    feature_4_bullet_2: 'Çalışan eğitim modülleri',
    feature_4_bullet_3: 'Otomatik bildirim sistemleri',
    feature_4_bullet_4: 'Esnek entegrasyon seçenekleri',
    feature_4_bullet_5: 'Özel rapor tasarımı',

    how_title: 'Nasıl Çalışır?',
    how_step_1_title: 'JSON Yükleme',
    how_step_1_desc: 'Çalışan bilgilerinizi JSON formatında yükleyin',
    how_step_2_title: 'Telegram Entegrasyonu',
    how_step_2_desc: 'Bot\'unuzu Telegram\'a 5 dakikada entegre edin',
    how_step_3_title: 'Çalışan Kayıt',
    how_step_3_desc: 'Çalışanlarınız tek mesajla sisteme kayıt olur',
    how_step_4_title: 'Otomatik Çalışma',
    how_step_4_desc: 'Sistem 7/24 otomatik çalışmaya başlar',

    pricing_title: 'Size Uygun Planı Seçin',
    pricing_monthly: 'Aylık',
    pricing_yearly: 'Yıllık',
    pricing_save: 'tasarruf',

    plan_1_name: 'Başlangıç',
    plan_1_badge: 'KOBİ için ideal',
    plan_1_price: '$59.99',
    plan_1_period: '/ay',
    plan_1_yearly_price: '$49.99',
    plan_1_yearly_save: '%17 tasarruf',
    plan_1_cta: 'Hemen Başla',
    plan_1_feat_1: 'Telegram AI Asistan',
    plan_1_feat_2: '40 çalışana kadar',
    plan_1_feat_3: 'Lokasyon tabanlı devamsızlık',
    plan_1_feat_4: '20 rapor/ay',
    plan_1_feat_5: 'Maaş hesaplama',
    plan_1_feat_6: '5 yönetici erişimi',
    plan_1_feat_7: 'İşe alım asistanı yok',

    plan_2_name: 'Profesyonel',
    plan_2_badge: 'En popüler',
    plan_2_price: '$69.99',
    plan_2_period: '/ay',
    plan_2_yearly_price: '$57.99',
    plan_2_yearly_save: '%17 tasarruf',
    plan_2_cta: 'Hemen Başla',
    plan_2_feat_1: 'Tüm Başlangıç özellikleri',
    plan_2_feat_2: '90 çalışana kadar',
    plan_2_feat_3: '40 rapor/ay',
    plan_2_feat_4: '7 yönetici erişimi',
    plan_2_feat_5: 'Öncelikli destek',
    plan_2_feat_6: 'İşe alım asistanı yok',

    plan_3_name: 'Kurumsal',
    plan_3_badge: 'Tam özellik',
    plan_3_price: '$109.99',
    plan_3_period: '/ay',
    plan_3_yearly_price: '$90.99',
    plan_3_yearly_save: '%17 tasarruf',
    plan_3_cta: 'Hemen Başla',
    plan_3_feat_1: 'Tüm Profesyonel özellikleri',
    plan_3_feat_2: '100 çalışana kadar',
    plan_3_feat_3: 'AI İşe Alım Asistanı',
    plan_3_feat_4: '50 rapor/ay',
    plan_3_feat_5: 'Ayda 5 işe alım',
    plan_3_feat_6: 'Çalışan eğitim modülleri',
    plan_3_feat_7: 'Otomatik sözleşme imzalama',
    plan_3_feat_8: '7 yönetici erişimi',

    plan_4_name: 'Özel Çözüm',
    plan_4_badge: 'Büyük işletmeler',
    plan_4_price: 'Özel Teklif',
    plan_4_period: '',
    plan_4_cta: 'İletişime Geçin',
    plan_4_feat_1: 'Sınırsız çalışan',
    plan_4_feat_2: 'Tüm özellikler aktif',
    plan_4_feat_3: 'Özel entegrasyonlar',
    plan_4_feat_4: 'Özel AI modelleri',
    plan_4_feat_5: 'Dedike destek ekibi',
    plan_4_feat_6: 'SLA garantisi',

    testimonials_title: 'Müşterilerimiz Ne Diyor?',
    testimonial_1_text: 'UpOne sayesinde 80 çalışanımızın devamsızlık takibini tamamen otomatikleştirdik. Aylık raporlama süresi 3 günden 1 saate düştü. Sistem kurulumu gerçekten 5 dakika sürdü!',
    testimonial_1_name: 'Mehmet Yılmaz',
    testimonial_1_role: 'İK Müdürü',
    testimonial_1_company: 'Otel İşletmesi - 80 Çalışan',
    testimonial_2_text: 'İzin yönetimi çok kolaylaştı. Çalışanlar Telegram\'dan izin istiyor, sistem otomatik hallediyor. Yönetici olarak sadece özel durumları onaylıyorum. Harika bir sistem!',
    testimonial_2_name: 'Ayşe Demir',
    testimonial_2_role: 'Genel Müdür',
    testimonial_2_company: 'Üretim KOBİ - 45 Çalışan',
    testimonial_3_text: 'Startup olarak hızlı büyüyoruz. UpOne\'ın işe alım asistanı CV\'leri otomatik değerlendiriyor, zamandan çok tasarruf ettik. AI mülakat soruları çok kaliteli!',
    testimonial_3_name: 'Can Öztürk',
    testimonial_3_role: 'Kurucu Ortak',
    testimonial_3_company: 'Startup - 25 Çalışan',

    industries_title: 'Hangi Sektörlere Hizmet Veriyoruz?',
    industry_1_title: 'Sanayi & Üretim',
    industry_1_desc: 'Vardiya takibi ve üretim personeli yönetimi',
    industry_2_title: 'Otelcilik & Turizm',
    industry_2_desc: 'Sezonluk personel ve çok lokasyonlu yönetim',
    industry_3_title: 'Startup & Teknoloji',
    industry_3_desc: 'Hızlı büyüme ve esnek çalışma modelleri',

    faq_title: 'Sık Sorulan Sorular',
    faq_1_q: 'Kurulum ne kadar sürer?',
    faq_1_a: 'Kurulum sadece 5 dakika sürer. Çalışan bilgilerinizi JSON formatında yükleyin, Telegram bot\'unuzu entegre edin ve çalışanlarınız sisteme kayıt olsun. İlk raporunuzu 1 saat içinde alabilirsiniz.',
    faq_2_q: 'Telegram neden kullanıyorsunuz?',
    faq_2_a: 'Telegram güvenli, hızlı ve çalışanların zaten kullandığı bir platform. Mobil uygulama indirmeye gerek yok, bot üzerinden tüm işlemler yapılabiliyor. Ayrıca lokasyon paylaşımı çok kolay.',
    faq_3_q: 'Veri güvenliği nasıl sağlanıyor?',
    faq_3_a: 'Tüm veriler şifreli olarak saklanır. Telegram\'ın end-to-end şifreleme altyapısını kullanıyoruz. Verileriniz yedeklenir ve KVKK uyumludur. Hiçbir veri üçüncü taraflarla paylaşılmaz.',
    faq_4_q: 'Ücretsiz deneme var mı?',
    faq_4_a: 'Şu anda ücretsiz deneme sunmuyoruz, ancak WhatsApp üzerinden bizimle iletişime geçerek ücretsiz demo görüşmesi talep edebilirsiniz. Sistemi detaylı şekilde gösteriyoruz.',
    faq_5_q: 'Mevcut sistemlerimle entegre olur mu?',
    faq_5_a: 'Evet, UpOne esnek entegrasyon seçenekleri sunar. Maaş bordro sistemleri, ERP yazılımları ve diğer İK araçlarıyla entegre olabilir. Özel entegrasyon ihtiyaçlarınız için bizimle iletişime geçin.',
    faq_6_q: 'Hangi raporlar sunuluyor?',
    faq_6_a: 'Günlük/aylık devamsızlık raporları, geç kalma analizleri, izin kullanım raporları, departman bazlı raporlar, maaş hesaplama raporları ve özel raporlar oluşturabilirsiniz.',
    faq_7_q: 'Mobil uygulamanız var mı?',
    faq_7_a: 'Telegram zaten bir mobil uygulama olduğu için ayrı bir uygulama geliştirmedik. Çalışanlar Telegram üzerinden tüm işlemleri yapabilir. Yöneticiler için web paneli mevcut.',
    faq_8_q: 'İptal politikanız nedir?',
    faq_8_a: 'Aboneliğinizi istediğiniz zaman iptal edebilirsiniz. İptal sonrası verileriniz 30 gün boyunca saklanır ve talep etmeniz halinde size iletilir. Otomatik yenileme yoktur.',

    cta_title: 'İK Süreçlerinizi Bugün Otomatikleştirin',
    cta_subtitle: 'Kurulum 5 dakika, ilk rapor 1 saat içinde',
    cta_whatsapp: 'WhatsApp\'tan Hemen Başlayın',
    cta_secondary: 'Fiyatlandırmayı İncele',

    footer_about: 'UpOne, yapay zeka destekli İK otomasyon platformudur. Telegram üzerinden çalışan sistemimiz ile devamsızlık takibi, izin yönetimi ve işe alım süreçlerinizi otomatikleştirin.',
    footer_product: 'Ürün',
    footer_company: 'Şirket',
    footer_support: 'Destek',
    footer_contact: 'İletişim',
    footer_features: 'Özellikler',
    footer_pricing: 'Fiyatlandırma',
    footer_how: 'Nasıl Çalışır',
    footer_demo: 'Demo İste',
    footer_about_us: 'Hakkımızda',
    footer_contact_us: 'İletişim',
    footer_blog: 'Blog',
    footer_careers: 'Kariyer',
    footer_help: 'Yardım Merkezi',
    footer_whatsapp: 'WhatsApp Destek',
    footer_docs: 'Dokümantasyon',
    footer_faq: 'SSS',
    footer_phone: '+90 543 603 71 90',
    footer_email: 'info@upone.ai',
    footer_address: 'İstanbul, Türkiye',
    footer_rights: '© 2024 UpOne. Tüm hakları saklıdır.',
    footer_privacy: 'Gizlilik Politikası',
    footer_terms: 'Kullanım Şartları',
    footer_cookies: 'Çerez Politikası',

    references_title: 'Referanslarımız',
    references_subtitle: 'Türkiye\'nin önde gelen şirketleri UpOne\'a güveniyor',

    success_stories_title: 'Başarı Hikayeleri',
    success_stories_subtitle: 'Müşterilerimizin UpOne ile elde ettiği başarıları keşfedin',
    success_stories_empty: 'Henüz başarı hikayesi eklenmemiş.',

    about_title: 'Hakkımızda',
    about_subtitle: 'UpOne: İnsan Kaynakları Yönetiminde Yapay Zeka Devrimi',
    about_section_1_title: 'Misyonumuz',
    about_section_1_text: 'UpOne olarak, işletmelerin insan kaynakları süreçlerini yapay zeka ile otomatikleştirerek verimliliği artırmayı ve insan odaklı yönetimi kolaylaştırmayı amaçlıyoruz. Telegram üzerinden çalışan AI asistanımız, kurulumu 5 dakika süren, kullanımı son derece basit bir çözüm sunuyor.',
    about_section_2_title: 'Vizyonumuz',
    about_section_2_text: 'Türkiye\'nin her ölçekteki işletmesinin erişebileceği, modern ve akıllı bir İK yönetim platformu olmak. İnsan kaynakları departmanlarını manuel işlerden kurtararak, stratejik kararlar almalarına olanak sağlamak istiyoruz.',
    about_section_3_title: 'Değerlerimiz',
    about_section_3_text: 'İnovasyon, şeffaflık, müşteri memnuniyeti ve sürekli gelişim değerlerimizin merkezinde yer alıyor. Her gün daha iyi bir ürün sunmak için çalışıyor, müşteri geri bildirimlerini dinliyor ve teknolojik gelişmeleri yakından takip ediyoruz.',
    about_team_title: 'Ekibimiz',
    about_team_text: 'UpOne ekibi, yapay zeka, yazılım geliştirme ve insan kaynakları alanlarında uzman profesyonellerden oluşuyor. Müşterilerimize en iyi deneyimi sunmak için tutkuyla çalışıyoruz.',

    why_us_title: 'Neden UpOne?',
    why_us_subtitle: 'Rakiplerimizden farklı kılan özellikleri keşfedin',
    why_us_reason_1_title: '5 Dakikada Kurulum',
    why_us_reason_1_desc: 'Karmaşık kurulum süreçleri yok. JSON dosyanızı yükleyin, bot\'unuzu entegre edin ve hemen kullanmaya başlayın.',
    why_us_reason_2_title: 'Telegram Tabanlı',
    why_us_reason_2_desc: 'Çalışanlarınız zaten kullandığı Telegram üzerinden tüm işlemleri yapabilir. Yeni bir uygulama öğrenmeye gerek yok.',
    why_us_reason_3_title: '%100 Otomatik',
    why_us_reason_3_desc: 'AI asistanımız devamsızlık kontrolü, izin onayları ve raporlamayı otomatik halleder. Manuel işlem gerektirmez.',
    why_us_reason_4_title: 'Yapay Zeka Destekli',
    why_us_reason_4_desc: 'Doğal dil işleme ile çalışanlarınız kolayca talep oluşturabilir. AI asistan akıllı kararlar verir.',
    why_us_reason_5_title: 'Uygun Fiyat',
    why_us_reason_5_desc: 'Her bütçeye uygun planlarımızla, büyük bütçeler gerektirmeyen modern İK çözümü sunuyoruz.',
    why_us_reason_6_title: '7/24 Destek',
    why_us_reason_6_desc: 'WhatsApp üzerinden her zaman ulaşabileceğiniz destek ekibimiz sorularınızı anında yanıtlar.',
  },
  en: {
    nav_home: 'Home',
    nav_features: 'Features',
    nav_pricing: 'Pricing',
    nav_references: 'References',
    nav_success_stories: 'Success Stories',
    nav_about: 'About Us',
    nav_why_us: 'Why Us?',
    nav_contact: 'Contact',
    nav_cta: 'Get Started',

    hero_title: 'Manage HR with Artificial Intelligence',
    hero_subtitle: 'Fully automate attendance tracking, leave management and recruitment processes. Your AI assistant running on Telegram, setup in 5 minutes.',
    hero_cta_primary: 'Request Free Demo',
    hero_cta_secondary: 'WhatsApp Support',

    trust_1: '5 Minute Setup',
    trust_2: '100% Automated',
    trust_3: 'Telegram Based',
    trust_4: 'AI Powered',

    stat_1_value: '1,000+',
    stat_1_label: 'Happy Businesses',
    stat_2_value: '50,000+',
    stat_2_label: 'Employees Tracked',
    stat_3_value: '95%',
    stat_3_label: 'Time Savings',
    stat_4_value: '24/7',
    stat_4_label: 'Automated System',

    features_title: 'Features',

    feature_1_title: 'Location-Based Smart Attendance Tracking',
    feature_1_desc: 'Your employees check in and out by sharing location via Telegram. AI assistant provides automatic attendance control, late arrival notifications and daily reports.',
    feature_1_bullet_1: 'Real-time location verification',
    feature_1_bullet_2: 'Automatic check-in/check-out records',
    feature_1_bullet_3: 'Daily/monthly automatic reports',
    feature_1_bullet_4: 'Late arrival notifications to managers',
    feature_1_bullet_5: 'Payroll calculation integration',

    feature_2_title: 'AI-Powered Automatic Leave Approval',
    feature_2_desc: 'Employees request leave in natural language via Telegram. AI assistant automatically approves sick leave, routes other requests to manager.',
    feature_2_bullet_1: 'Natural language processing for leave requests',
    feature_2_bullet_2: 'Automatic approval for single-day sick leave',
    feature_2_bullet_3: 'Manager approval system',
    feature_2_bullet_4: 'Remaining leave calculation',
    feature_2_bullet_5: 'Leave history reports',

    feature_3_title: 'Automatic CV Processing and Candidate Evaluation',
    feature_3_desc: 'All CVs for your position are analyzed, scored and best candidates are identified by AI. AI generates interview questions.',
    feature_3_bullet_1: 'Automatic CV parsing and scoring',
    feature_3_bullet_2: 'Candidate ranking algorithm',
    feature_3_bullet_3: 'AI interview questions',
    feature_3_bullet_4: 'Automatic interview scheduling',
    feature_3_bullet_5: 'Candidate communication management',

    feature_4_title: 'Custom AI Automations for Your Business',
    feature_4_desc: 'Customizable automation systems according to your needs. Contract management, training tracking, notification systems and more.',
    feature_4_bullet_1: 'Automatic contract signing',
    feature_4_bullet_2: 'Employee training modules',
    feature_4_bullet_3: 'Automatic notification systems',
    feature_4_bullet_4: 'Flexible integration options',
    feature_4_bullet_5: 'Custom report design',

    how_title: 'How It Works?',
    how_step_1_title: 'Upload JSON',
    how_step_1_desc: 'Upload your employee information in JSON format',
    how_step_2_title: 'Telegram Integration',
    how_step_2_desc: 'Integrate your bot to Telegram in 5 minutes',
    how_step_3_title: 'Employee Registration',
    how_step_3_desc: 'Your employees register to the system with one message',
    how_step_4_title: 'Automatic Operation',
    how_step_4_desc: 'System starts working automatically 24/7',

    pricing_title: 'Choose Your Perfect Plan',
    pricing_monthly: 'Monthly',
    pricing_yearly: 'Yearly',
    pricing_save: 'save',

    plan_1_name: 'Starter',
    plan_1_badge: 'Ideal for SME',
    plan_1_price: '$59.99',
    plan_1_period: '/mo',
    plan_1_yearly_price: '$49.99',
    plan_1_yearly_save: '17% save',
    plan_1_cta: 'Get Started',
    plan_1_feat_1: 'Telegram AI Assistant',
    plan_1_feat_2: 'Up to 40 employees',
    plan_1_feat_3: 'Location-based attendance',
    plan_1_feat_4: '20 reports/month',
    plan_1_feat_5: 'Payroll calculation',
    plan_1_feat_6: '5 manager access',
    plan_1_feat_7: 'No recruitment assistant',

    plan_2_name: 'Professional',
    plan_2_badge: 'Most popular',
    plan_2_price: '$69.99',
    plan_2_period: '/mo',
    plan_2_yearly_price: '$57.99',
    plan_2_yearly_save: '17% save',
    plan_2_cta: 'Get Started',
    plan_2_feat_1: 'All Starter features',
    plan_2_feat_2: 'Up to 90 employees',
    plan_2_feat_3: '40 reports/month',
    plan_2_feat_4: '7 manager access',
    plan_2_feat_5: 'Priority support',
    plan_2_feat_6: 'No recruitment assistant',

    plan_3_name: 'Enterprise',
    plan_3_badge: 'Full features',
    plan_3_price: '$109.99',
    plan_3_period: '/mo',
    plan_3_yearly_price: '$90.99',
    plan_3_yearly_save: '17% save',
    plan_3_cta: 'Get Started',
    plan_3_feat_1: 'All Professional features',
    plan_3_feat_2: 'Up to 100 employees',
    plan_3_feat_3: 'AI Recruitment Assistant',
    plan_3_feat_4: '50 reports/month',
    plan_3_feat_5: '5 recruitments per month',
    plan_3_feat_6: 'Employee training modules',
    plan_3_feat_7: 'Automatic contract signing',
    plan_3_feat_8: '7 manager access',

    plan_4_name: 'Custom Solution',
    plan_4_badge: 'Large enterprises',
    plan_4_price: 'Custom Quote',
    plan_4_period: '',
    plan_4_cta: 'Contact Us',
    plan_4_feat_1: 'Unlimited employees',
    plan_4_feat_2: 'All features active',
    plan_4_feat_3: 'Custom integrations',
    plan_4_feat_4: 'Custom AI models',
    plan_4_feat_5: 'Dedicated support team',
    plan_4_feat_6: 'SLA guarantee',

    testimonials_title: 'What Our Clients Say',
    testimonial_1_text: 'With UpOne, we fully automated attendance tracking for our 80 employees. Monthly reporting time dropped from 3 days to 1 hour. The system setup really took 5 minutes!',
    testimonial_1_name: 'Mehmet Yılmaz',
    testimonial_1_role: 'HR Manager',
    testimonial_1_company: 'Hotel Business - 80 Employees',
    testimonial_2_text: 'Leave management became so easy. Employees request leave via Telegram, the system handles it automatically. As a manager, I only approve special cases. Great system!',
    testimonial_2_name: 'Ayşe Demir',
    testimonial_2_role: 'General Manager',
    testimonial_2_company: 'Manufacturing SME - 45 Employees',
    testimonial_3_text: 'We\'re growing fast as a startup. UpOne\'s recruitment assistant automatically evaluates CVs, saving us a lot of time. AI interview questions are very high quality!',
    testimonial_3_name: 'Can Öztürk',
    testimonial_3_role: 'Co-Founder',
    testimonial_3_company: 'Startup - 25 Employees',

    industries_title: 'Which Industries We Serve',
    industry_1_title: 'Industry & Manufacturing',
    industry_1_desc: 'Shift tracking and production personnel management',
    industry_2_title: 'Hospitality & Tourism',
    industry_2_desc: 'Seasonal staff and multi-location management',
    industry_3_title: 'Startup & Technology',
    industry_3_desc: 'Rapid growth and flexible work models',

    faq_title: 'Frequently Asked Questions',
    faq_1_q: 'How long does setup take?',
    faq_1_a: 'Setup takes only 5 minutes. Upload your employee information in JSON format, integrate your Telegram bot and have your employees register to the system. You can receive your first report within 1 hour.',
    faq_2_q: 'Why do you use Telegram?',
    faq_2_a: 'Telegram is secure, fast and a platform employees already use. No need to download a mobile app, all operations can be done via bot. Also, location sharing is very easy.',
    faq_3_q: 'How is data security ensured?',
    faq_3_a: 'All data is stored encrypted. We use Telegram\'s end-to-end encryption infrastructure. Your data is backed up and GDPR compliant. No data is shared with third parties.',
    faq_4_q: 'Is there a free trial?',
    faq_4_a: 'We don\'t currently offer a free trial, but you can contact us via WhatsApp to request a free demo session. We show the system in detail.',
    faq_5_q: 'Does it integrate with my existing systems?',
    faq_5_a: 'Yes, UpOne offers flexible integration options. It can integrate with payroll systems, ERP software and other HR tools. Contact us for your custom integration needs.',
    faq_6_q: 'What reports are offered?',
    faq_6_a: 'Daily/monthly attendance reports, tardiness analysis, leave usage reports, department-based reports, payroll calculation reports and you can create custom reports.',
    faq_7_q: 'Do you have a mobile app?',
    faq_7_a: 'Since Telegram is already a mobile app, we didn\'t develop a separate app. Employees can do all operations via Telegram. A web panel is available for managers.',
    faq_8_q: 'What is your cancellation policy?',
    faq_8_a: 'You can cancel your subscription at any time. After cancellation, your data is kept for 30 days and will be delivered to you upon request. There is no automatic renewal.',

    cta_title: 'Automate Your HR Processes Today',
    cta_subtitle: 'Setup in 5 minutes, first report within 1 hour',
    cta_whatsapp: 'Start Now on WhatsApp',
    cta_secondary: 'View Pricing',

    footer_about: 'UpOne is an AI-powered HR automation platform. Automate your attendance tracking, leave management and recruitment processes with our system running on Telegram.',
    footer_product: 'Product',
    footer_company: 'Company',
    footer_support: 'Support',
    footer_contact: 'Contact',
    footer_features: 'Features',
    footer_pricing: 'Pricing',
    footer_how: 'How It Works',
    footer_demo: 'Request Demo',
    footer_about_us: 'About Us',
    footer_contact_us: 'Contact',
    footer_blog: 'Blog',
    footer_careers: 'Careers',
    footer_help: 'Help Center',
    footer_whatsapp: 'WhatsApp Support',
    footer_docs: 'Documentation',
    footer_faq: 'FAQ',
    footer_phone: '+90 543 603 71 90',
    footer_email: 'info@upone.ai',
    footer_address: 'Istanbul, Turkey',
    footer_rights: '© 2024 UpOne. All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_cookies: 'Cookie Policy',

    references_title: 'Our References',
    references_subtitle: 'Turkey\'s leading companies trust UpOne',

    success_stories_title: 'Success Stories',
    success_stories_subtitle: 'Discover the success our clients achieved with UpOne',
    success_stories_empty: 'No success stories added yet.',

    about_title: 'About Us',
    about_subtitle: 'UpOne: The AI Revolution in Human Resources Management',
    about_section_1_title: 'Our Mission',
    about_section_1_text: 'As UpOne, we aim to increase efficiency and facilitate human-centered management by automating business human resources processes with artificial intelligence. Our AI assistant running on Telegram offers a solution that takes 5 minutes to set up and is extremely simple to use.',
    about_section_2_title: 'Our Vision',
    about_section_2_text: 'To be a modern and intelligent HR management platform accessible to businesses of all sizes in Turkey. We want to free human resources departments from manual work and enable them to make strategic decisions.',
    about_section_3_title: 'Our Values',
    about_section_3_text: 'Innovation, transparency, customer satisfaction and continuous improvement are at the center of our values. We work to offer a better product every day, listen to customer feedback and closely follow technological developments.',
    about_team_title: 'Our Team',
    about_team_text: 'The UpOne team consists of professionals specialized in artificial intelligence, software development and human resources. We work passionately to provide the best experience to our customers.',

    why_us_title: 'Why UpOne?',
    why_us_subtitle: 'Discover the features that set us apart from competitors',
    why_us_reason_1_title: '5 Minute Setup',
    why_us_reason_1_desc: 'No complex installation processes. Upload your JSON file, integrate your bot and start using immediately.',
    why_us_reason_2_title: 'Telegram Based',
    why_us_reason_2_desc: 'Your employees can do all operations via Telegram they already use. No need to learn a new application.',
    why_us_reason_3_title: '100% Automatic',
    why_us_reason_3_desc: 'Our AI assistant automatically handles attendance control, leave approvals and reporting. No manual processing required.',
    why_us_reason_4_title: 'AI Powered',
    why_us_reason_4_desc: 'Your employees can easily create requests with natural language processing. AI assistant makes smart decisions.',
    why_us_reason_5_title: 'Affordable Price',
    why_us_reason_5_desc: 'With plans suitable for every budget, we offer modern HR solutions that don\'t require large budgets.',
    why_us_reason_6_title: '24/7 Support',
    why_us_reason_6_desc: 'Our support team, which you can always reach via WhatsApp, answers your questions instantly.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.tr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
