import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    nav_home: 'Ana Sayfa',
    nav_features: 'Özellikler',
    nav_pricing: 'Fiyatlandırma',
    nav_references: 'Referanslar',
    nav_success_stories: 'Başarı Hikayeleri',
    nav_about: 'Hakkımızda',
    nav_why_us: 'Neden Biz?',
    nav_contact: 'İletişim',
    nav_cta: 'Hemen Başla',

    hero_title: 'İnsan Kaynaklarını Yapay Zeka ile Yönetin',
    hero_subtitle: 'Devamsızlık takibi, izin yönetimi ve işe alım süreçlerinizi tamamen otomatikleştirin. Telegram üzerinden çalışan, kurulumu 5 dakika süren AI asistanınız.',
    hero_cta_primary: 'Ücretsiz Demo İsteyin',
    hero_cta_secondary: 'WhatsApp Destek',

    trust_1: '5 Dakikada Kurulum',
    trust_2: '100% Otomatik',
    trust_3: 'Telegram Tabanlı',
    trust_4: 'AI Destekli',

    stat_1_value: '80+',
    stat_1_label: 'Mutlu İşletme',
    stat_2_value: '5,000+',
    stat_2_label: 'Çalışan Takibi',
    stat_3_value: '%90',
    stat_3_label: 'Zaman Tasarrufu',
    stat_4_value: '24/7',
    stat_4_label: 'Yapay Zeka Raporları',

    features_title: 'Özellikler',

    feature_1_title: 'Lokasyon Bazlı Akıllı Devamsızlık Takibi',
    feature_1_desc: 'Çalışanlarınız Telegram üzerinden lokasyon paylaşarak rahatlıkla giriş-çıkış yapar. AI asistan otomatik devamsızlık kontrolü, geç kalma bildirimleri ve günlük raporlar sunar. İşletmenizin özel çalışma standartlarına %100 esneklik.',
    feature_1_bullet_1: 'Gerçek zamanlı lokasyon doğrulama',
    feature_1_bullet_2: 'Vardiya saatlerine entegrasyon ve fazla mesai takibi',

    feature_1_bullet_3: 'Otomatik giriş-çıkış kayıtları',
    feature_1_bullet_4: 'Günlük/aylık otomatik raporlar ve yapay zeka uyarıları',
    feature_1_bullet_5: 'Geç kalma bildirimleri yöneticilere',
    feature_1_bullet_6 : 'Maaş hesaplama entegrasyonu',

    feature_2_title: 'Yapay Zeka Destekli Otomatik İzin Onayı',
    feature_2_desc: 'Çalışanlar Telegram\'dan doğal dille izin talep eder. AI asistan şirket politikanıza göre istediğiniz durumlarda otomatik onay vererek prosedürünüzü uygularken dilediğiniz talepleri yönetici onayına yönlendirir.',
    feature_2_bullet_1: 'Doğal dil işleme ile izin talebi',
    feature_2_bullet_2: '%100 esneklik',
    feature_2_bullet_3: 'Yönetici onay sistemi',
    feature_2_bullet_4: 'Kalan izin hesaplama',
    feature_2_bullet_5: 'İzin geçmişi raporları ve motivasyon takibi',


    feature_3_title: 'Otomatik CV İşleme ve Aday Değerlendirme',
    feature_3_desc: 'Pozisyonunuz için gelen tüm CV\'ler AI tarafından analiz edilir, puanlanır ve en uygun adaylar belirlenir. Mülakat sorularını AI oluşturur.',
    feature_3_bullet_1: 'Otomatik CV inceleme ve puanlama',
    feature_3_bullet_2: 'Aday sıralama algoritması',
    feature_3_bullet_3: 'AI mülakat soruları',
    feature_3_bullet_4: 'Otomatik görüşme planlama',
    feature_3_bullet_5: 'Aday iletişim yönetimi',

    feature_4_title: 'İşletmenize Özel AI Otomasyonları',
    feature_4_desc: 'İhtiyaçlarınıza göre özelleştirilebilir otomasyon sistemleri. Chat asistan (müşteri destek, tedarikçi...), otomatik mail asistanları, bildirim sistemleri, planlayıcılar ve daha fazlası.',
    feature_4_bullet_1: 'Chat asistanı',
    feature_4_bullet_2: 'Müşteri bulma ajanları',
    feature_4_bullet_3: 'Otomatik bildirim sistemleri',
    feature_4_bullet_4: 'Akıllı tam otomatik mail asistanları',
    feature_4_bullet_5: 'Özel rapor tasarımları',

    how_title: 'Nasıl Çalışır?',
    how_step_1_title: 'Excel Yükleme',
    how_step_1_desc: 'Çalışan bilgilerinizi Excel formatında yükleyin',
    how_step_2_title: 'Telegram Entegrasyonu',
    how_step_2_desc: 'Bot\'unuzu Telegram\'a 5 dakikada entegre edin',
    how_step_3_title: 'Çalışan Kayıt',
    how_step_3_desc: 'Çalışanlarınız tek mesajla sisteme kayıt olur',
    how_step_4_title: 'Otomatik Çalışma',
    how_step_4_desc: 'Sistem 7/24 otomatik çalışmaya başlar',

    pricing_title: 'Size Uygun Planı Seçin',
    pricing_monthly: 'Aylık',
    pricing_yearly: 'Yıllık',
    pricing_save: 'tasarruf',

    plan_1_name: 'Başlangıç',
    plan_1_badge: 'KOBİ için ideal',
    plan_1_price: '$59.99',
    plan_1_period: '/ay',
    plan_1_yearly_price: '$49.99',
    plan_1_yearly_save: '%17 tasarruf',
    plan_1_cta: 'Hemen Başla',
    plan_1_feat_1: 'Telegram AI Asistan',
    plan_1_feat_2: '40 çalışana kadar',
    plan_1_feat_3: 'Lokasyon tabanlı devamsızlık',
    plan_1_feat_4: '20 rapor/ay',
    plan_1_feat_5: 'Maaş hesaplama',
    plan_1_feat_6: '5 yönetici erişimi',
    plan_1_feat_7: 'İşe alım asistanı yok',

    plan_2_name: 'Profesyonel',
    plan_2_badge: 'En popüler',
    plan_2_price: '$69.99',
    plan_2_period: '/ay',
    plan_2_yearly_price: '$57.99',
    plan_2_yearly_save: '%17 tasarruf',
    plan_2_cta: 'Hemen Başla',
    plan_2_feat_1: 'Tüm Başlangıç özellikleri',
    plan_2_feat_2: '90 çalışana kadar',
    plan_2_feat_3: '40 rapor/ay',
    plan_2_feat_4: '7 yönetici erişimi',
    plan_2_feat_5: 'Öncelikli destek',
    plan_2_feat_6: 'İşe alım asistanı yok',

    plan_3_name: 'Kurumsal',
    plan_3_badge: 'Tam özellik',
    plan_3_price: '$109.99',
    plan_3_period: '/ay',
    plan_3_yearly_price: '$90.99',
    plan_3_yearly_save: '%17 tasarruf',
    plan_3_cta: 'Hemen Başla',
    plan_3_feat_1: 'Tüm Profesyonel özellikleri',
    plan_3_feat_2: '100 çalışana kadar',
    plan_3_feat_3: 'AI İşe Alım Asistanı',
    plan_3_feat_4: '50 rapor/ay',
    plan_3_feat_5: 'Ayda 5 işe alım',
    plan_3_feat_6: 'Çalışan eğitim modülleri',
    plan_3_feat_7: 'Otomatik sözleşme imzalama',
    plan_3_feat_8: '7 yönetici erişimi',

    plan_4_name: 'Özel Çözüm',
    plan_4_badge: 'Büyük işletmeler',
    plan_4_price: 'Özel Teklif',
    plan_4_period: '',
    plan_4_cta: 'İletişime Geçin',
    plan_4_feat_1: 'Sınırsız çalışan',
    plan_4_feat_2: 'Tüm özellikler aktif',
    plan_4_feat_3: 'Özel entegrasyonlar',
    plan_4_feat_4: 'Özel AI modelleri',
    plan_4_feat_5: 'Dedike destek ekibi',
    plan_4_feat_6: 'SLA garantisi',

    testimonials_title: 'Müşterilerimiz Ne Diyor?',
    testimonial_1_text: 'UpOne sayesinde 45 çalışanımızın devamsızlık takibini tamamen otomatikleştirdik. Aylık raporlama ve puantaj süresi 3 günden 1 saate düştü. Ve ek yazılımlar gerekmediği için kullanım açısından çok rahattık.',
    testimonial_1_name: 'Elif Büşra Şimşek',
    testimonial_1_role: 'MThan ',
    testimonial_1_company: 'Mimarlık Ofisi - 50 Çalışan',
    testimonial_2_text: 'İzin yönetimi çok kolaylaştı. Çalışanlar Telegram\'dan izin istiyor, sistem otomatik hallediyor. Yıllık izin takibi ve vardiya yönetimi konusunda bizi çok rahatlattı. Yönetici olarak sadece özel durumları onaylıyorum. Harika bir sistem!',
    testimonial_2_name: 'Ali Asaf Küçük',
    testimonial_2_role: 'İşletme Sahibi',
    testimonial_2_company: 'Lojistik - 55 Çalışan',
    testimonial_3_text: 'Startup olarak hızlı büyüyoruz. UpOne\'ın işe alım asistanı CV\'leri otomatik değerlendiriyor, zamandan çok tasarruf ettik. AI mülakat soruları çok kaliteli ve adayları ölçme konusunda başarılı.',
    testimonial_3_name: 'Osman Tarık Özer',
    testimonial_3_role: 'Kurucu Ortak',
    testimonial_3_company: 'Startup - 25 Çalışan',

    industries_title: 'Hangi Sektörlere Hizmet Veriyoruz?',
    industry_1_title: 'Sanayi & Üretim',
    industry_1_desc: 'Vardiya takibi ve üretim personeli yönetimi',
    industry_2_title: 'Otelcilik & Turizm',
    industry_2_desc: 'Sezonluk personel ve çok lokasyonlu yönetim',
    industry_3_title: 'Startup & Teknoloji',
    industry_3_desc: 'Hızlı büyüme ve esnek çalışma modelleri',

    faq_title: 'Sık Sorulan Sorular',
    faq_1_q: 'Kurulum ne kadar sürer?',
    faq_1_a: 'Kurulum sadece 5 dakika sürer. Çalışan bilgilerinizi Excel formatında yükleyin, Telegram bot\'unuzu entegre edin ve çalışanlarınız sisteme kayıt olsun. İlk raporunuzu 1 saat içinde alabilirsiniz.',
    faq_2_q: 'Telegram neden kullanıyorsunuz?',
    faq_2_a: 'Telegram güvenli, hızlı ve çalışanların zaten kullandığı bir platform. Mobil uygulama indirmeye gerek yok, bot üzerinden tüm işlemler yapılabiliyor. Ayrıca lokasyon paylaşımı çok kolay.',
    faq_3_q: 'Veri güvenliği nasıl sağlanıyor?',
    faq_3_a: 'Tüm veriler şifreli olarak saklanır. Telegram\'ın end-to-end şifreleme altyapısını kullanıyoruz. Verileriniz yedeklenir ve KVKK uyumludur. Hiçbir veri üçüncü taraflarla paylaşılmaz.',
    faq_4_q: 'Ücretsiz deneme var mı?',
    faq_4_a: 'Şu anda ücretsiz deneme sunmuyoruz, ancak WhatsApp üzerinden bizimle iletişime geçerek ücretsiz demo görüşmesi talep edebilirsiniz. Sistemi detaylı şekilde gösteriyoruz.',
    faq_5_q: 'Mevcut sistemlerimle entegre olur mu?',
    faq_5_a: 'Evet, UpOne esnek entegrasyon seçenekleri sunar. Maaş bordro sistemleri, ERP yazılımları ve diğer İK araçlarıyla entegre olabilir. Özel entegrasyon ihtiyaçlarınız için bizimle iletişime geçin.',
    faq_6_q: 'Hangi raporlar sunuluyor?',
    faq_6_a: 'Günlük/aylık devamsızlık raporları, geç kalma analizleri, izin kullanım raporları, departman bazlı raporlar, maaş hesaplama raporları ve özel raporlar oluşturabilirsiniz.',
    faq_7_q: 'Mobil uygulamanız var mı?',
    faq_7_a: 'Telegram zaten bir mobil uygulama olduğu için ayrı bir uygulama geliştirmedik. Çalışanlar Telegram üzerinden tüm işlemleri yapabilir. Yöneticiler için web paneli mevcut.',
    faq_8_q: 'İptal politikanız nedir?',
    faq_8_a: 'Aboneliğinizi istediğiniz zaman iptal edebilirsiniz. İptal sonrası verileriniz 30 gün boyunca saklanır ve talep etmeniz halinde size iletilir. Otomatik yenileme yoktur.',

    cta_title: 'İK Süreçlerinizi Bugün Otomatikleştirin ve tasarruf etmeye başlayın',
    cta_subtitle: 'Kurulum 5 dakika, ilk rapor 1 saat içinde',
    cta_whatsapp: 'WhatsApp\'tan Hemen Başlayın',
    cta_secondary: 'Fiyatlandırmayı İncele',

    footer_about: 'UpOne, yapay zeka destekli İK otomasyon platformudur. Telegram üzerinden çalışan sistemimiz ile devamsızlık takibi, izin yönetimi ve işe alım süreçlerinizi otomatikleştirin.',
    footer_product: 'Ürün',
    footer_company: 'Şirket',
    footer_support: 'Destek',
    footer_contact: 'İletişim',
    footer_features: 'Özellikler',
    footer_pricing: 'Fiyatlandırma',
    footer_how: 'Nasıl Çalışır',
    footer_demo: 'Demo İste',
    footer_about_us: 'Hakkımızda',
    footer_contact_us: 'İletişim',
    footer_blog: 'Blog',
    footer_careers: 'Kariyer',
    footer_help: 'Yardım Merkezi',
    footer_whatsapp: 'WhatsApp Destek',
    footer_docs: 'Dokümantasyon',
    footer_faq: 'SSS',
    footer_phone: '+90 543 603 71 90',
    footer_email: 'info@upone.ai',
    footer_address: 'Konya, Türkiye',
    footer_rights: '© 2024 UpOne. Tüm hakları saklıdır.',
    footer_privacy: 'Gizlilik Politikası',
    footer_terms: 'Kullanım Şartları',
    footer_cookies: 'Çerez Politikası',

    references_title: 'Referanslarımız',
    references_subtitle: 'Türkiye\'nin önde gelen şirketleri UpOne\'a güveniyor',

    success_stories_title: 'Başarı Hikayeleri',
    success_stories_subtitle: 'Müşterilerimizin UpOne ile elde ettiği başarıları keşfedin',
    success_stories_empty: 'Henüz başarı hikayesi eklenmemiş.',

    about_title: 'Hakkımızda',
    about_subtitle: 'UpOne: İnsan Kaynakları Yönetiminde Yapay Zeka Devrimi',
    about_section_1_title: 'Misyonumuz',
    about_section_1_text: 'UpOne olarak, işletmelerin insan kaynakları süreçlerini yapay zeka ile otomatikleştirerek verimliliği artırmayı ve insan odaklı yönetimi kolaylaştırmayı amaçlıyoruz. Telegram üzerinden çalışan AI asistanımız, kurulumu 5 dakika süren, kullanımı son derece basit bir çözüm sunuyor.',
    about_section_2_title: 'Vizyonumuz',
    about_section_2_text: 'Türkiye\'nin her ölçekteki işletmesinin erişebileceği, modern ve akıllı bir İK yönetim platformu olmak. İnsan kaynakları departmanlarını manuel işlerden kurtararak, stratejik kararlar almalarına olanak sağlamak istiyoruz.',
    about_section_3_title: 'Değerlerimiz',
    about_section_3_text: 'İnovasyon, şeffaflık, müşteri memnuniyeti ve sürekli gelişim değerlerimizin merkezinde yer alıyor. Her gün daha iyi bir ürün sunmak için çalışıyor, müşteri geri bildirimlerini dinliyor ve teknolojik gelişmeleri yakından takip ediyoruz.',
    about_team_title: 'Ekibimiz',
    about_team_text: 'UpOne ekibi, yapay zeka, yazılım geliştirme ve insan kaynakları alanlarında uzman profesyonellerden oluşuyor. Müşterilerimize en iyi deneyimi sunmak için tutkuyla çalışıyoruz.',

    why_us_title: 'Neden UpOne?',
    why_us_subtitle: 'Rakiplerimizden farklı kılan özellikleri keşfedin',
    why_us_reason_1_title: '5 Dakikada Kurulum',
    why_us_reason_1_desc: 'Karmaşık kurulum süreçleri yok. JSON dosyanızı yükleyin, bot\'unuzu entegre edin ve hemen kullanmaya başlayın.',
    why_us_reason_2_title: 'Telegram Tabanlı',
    why_us_reason_2_desc: 'Çalışanlarınız zaten kullandığı Telegram üzerinden tüm işlemleri yapabilir. Yeni bir uygulama öğrenmeye gerek yok.',
    why_us_reason_3_title: '%100 Otomatik',
    why_us_reason_3_desc: 'AI asistanımız devamsızlık kontrolü, izin onayları ve raporlamayı otomatik halleder. Manuel işlem gerektirmez.',
    why_us_reason_4_title: 'Yapay Zeka Destekli',
    why_us_reason_4_desc: 'Doğal dil işleme ile çalışanlarınız kolayca talep oluşturabilir. AI asistan akıllı kararlar verir.',
    why_us_reason_5_title: 'Uygun Fiyat',
    why_us_reason_5_desc: 'Her bütçeye uygun planlarımızla, büyük bütçeler gerektirmeyen modern İK çözümü sunuyoruz.',
    why_us_reason_6_title: '7/24 Destek',
    why_us_reason_6_desc: 'WhatsApp üzerinden her zaman ulaşabileceğiniz destek ekibimiz sorularınızı anında yanıtlar.',
  },
 en: {
  nav_home: 'Home',
  nav_features: 'Features',
  nav_pricing: 'Pricing',
  nav_references: 'References',
  nav_success_stories: 'Success Stories',
  nav_about: 'About',
  nav_why_us: 'Why Us?',
  nav_contact: 'Contact',
  nav_cta: 'Get Started',

  hero_title: 'Manage Human Resources with Artificial Intelligence',
  hero_subtitle: 'Automate attendance tracking, leave management, and recruitment processes. Your AI assistant runs on Telegram and is ready to use within 5 minutes.',
  hero_cta_primary: 'Request a Free Demo',
  hero_cta_secondary: 'WhatsApp Support',

  trust_1: '5-Minute Setup',
  trust_2: '100% Automated',
  trust_3: 'Telegram-Based',
  trust_4: 'AI-Powered',

  stat_1_value: '80+',
  stat_1_label: 'Happy Businesses',
  stat_2_value: '5,000+',
  stat_2_label: 'Employees Managed',
  stat_3_value: '90%',
  stat_3_label: 'Time Saved',
  stat_4_value: '24/7',
  stat_4_label: 'AI Reports',

  features_title: 'Features',

  feature_1_title: 'Location-Based Smart Attendance Tracking',
  feature_1_desc: 'Employees can easily clock in and out by sharing their location via Telegram. The AI assistant automatically checks attendance, sends lateness alerts, and generates daily reports. Fully flexible to your company’s working standards.',
  feature_1_bullet_1: 'Real-time location verification',
  feature_1_bullet_2: 'Shift integration and overtime tracking',
  feature_1_bullet_3: 'Automated clock-in/out records',
  feature_1_bullet_4: 'Daily/monthly automated reports and AI alerts',
  feature_1_bullet_5: 'Late arrival notifications for managers',
  feature_1_bullet_6: 'Payroll integration',

  feature_2_title: 'AI-Powered Leave Approval Automation',
  feature_2_desc: 'Employees request leave naturally through Telegram. The AI assistant automatically approves or routes requests according to your company policy.',
  feature_2_bullet_1: 'Natural language leave requests',
  feature_2_bullet_2: 'Fully customizable rules',
  feature_2_bullet_3: 'Manager approval workflow',
  feature_2_bullet_4: 'Leave balance calculation',
  feature_2_bullet_5: 'Leave history reports and engagement tracking',

  feature_3_title: 'Automated CV Processing and Candidate Evaluation',
  feature_3_desc: 'All incoming CVs are analyzed, scored, and ranked by AI. The assistant even generates interview questions automatically.',
  feature_3_bullet_1: 'Automated CV review and scoring',
  feature_3_bullet_2: 'Candidate ranking algorithm',
  feature_3_bullet_3: 'AI-generated interview questions',
  feature_3_bullet_4: 'Automatic interview scheduling',
  feature_3_bullet_5: 'Candidate communication management',

  feature_4_title: 'Custom AI Automations for Your Business',
  feature_4_desc: 'Tailored automation systems for your needs: chat assistants, supplier bots, email automation, notification systems, planners, and more.',
  feature_4_bullet_1: 'Chat assistant',
  feature_4_bullet_2: 'Lead generation agents',
  feature_4_bullet_3: 'Automated notification systems',
  feature_4_bullet_4: 'Intelligent email assistants',
  feature_4_bullet_5: 'Custom report designs',

  how_title: 'How It Works',
  how_step_1_title: 'Upload Excel File',
  how_step_1_desc: 'Upload your employee data in Excel format',
  how_step_2_title: 'Telegram Integration',
  how_step_2_desc: 'Integrate your bot with Telegram in just 5 minutes',
  how_step_3_title: 'Employee Registration',
  how_step_3_desc: 'Employees register to the system with a single message',
  how_step_4_title: 'Automated Operation',
  how_step_4_desc: 'The system runs automatically 24/7',

  pricing_title: 'Choose the Right Plan for You',
  pricing_monthly: 'Monthly',
  pricing_yearly: 'Yearly',
  pricing_save: 'save',

  plan_1_name: 'Starter',
  plan_1_badge: 'Ideal for SMEs',
  plan_1_price: '$59.99',
  plan_1_period: '/month',
  plan_1_yearly_price: '$49.99',
  plan_1_yearly_save: '17% off',
  plan_1_cta: 'Get Started',
  plan_1_feat_1: 'Telegram AI Assistant',
  plan_1_feat_2: 'Up to 40 employees',
  plan_1_feat_3: 'Location-based attendance tracking',
  plan_1_feat_4: '20 reports/month',
  plan_1_feat_5: 'Payroll calculation',
  plan_1_feat_6: '5 manager accounts',
  plan_1_feat_7: 'No recruitment assistant',

  plan_2_name: 'Professional',
  plan_2_badge: 'Most Popular',
  plan_2_price: '$69.99',
  plan_2_period: '/month',
  plan_2_yearly_price: '$57.99',
  plan_2_yearly_save: '17% off',
  plan_2_cta: 'Get Started',
  plan_2_feat_1: 'All Starter features',
  plan_2_feat_2: 'Up to 90 employees',
  plan_2_feat_3: '40 reports/month',
  plan_2_feat_4: '7 manager accounts',
  plan_2_feat_5: 'Priority support',
  plan_2_feat_6: 'No recruitment assistant',

  plan_3_name: 'Enterprise',
  plan_3_badge: 'Full Features',
  plan_3_price: '$109.99',
  plan_3_period: '/month',
  plan_3_yearly_price: '$90.99',
  plan_3_yearly_save: '17% off',
  plan_3_cta: 'Get Started',
  plan_3_feat_1: 'All Professional features',
  plan_3_feat_2: 'Up to 100 employees',
  plan_3_feat_3: 'AI Recruitment Assistant',
  plan_3_feat_4: '50 reports/month',
  plan_3_feat_5: 'Up to 5 hires/month',
  plan_3_feat_6: 'Employee training modules',
  plan_3_feat_7: 'Automated contract signing',
  plan_3_feat_8: '7 manager accounts',

  plan_4_name: 'Custom Solution',
  plan_4_badge: 'For Large Enterprises',
  plan_4_price: 'Custom Quote',
  plan_4_period: '',
  plan_4_cta: 'Contact Us',
  plan_4_feat_1: 'Unlimited employees',
  plan_4_feat_2: 'All features included',
  plan_4_feat_3: 'Custom integrations',
  plan_4_feat_4: 'Dedicated AI models',
  plan_4_feat_5: 'Dedicated support team',
  plan_4_feat_6: 'SLA guarantee',

  testimonials_title: 'What Our Clients Say',
  testimonial_1_text: 'Thanks to UpOne, we fully automated the attendance tracking of our 45 employees. Monthly reporting time dropped from 3 days to just 1 hour. It’s incredibly convenient since no extra software is required.',
  testimonial_1_name: 'Elif Büşra Şimşek',
  testimonial_1_role: 'Manager',
  testimonial_1_company: 'Architecture Office - 50 Employees',
  testimonial_2_text: 'Leave management became effortless. Employees request leave via Telegram, and the system handles it automatically. As a manager, I only review special cases. Excellent system!',
  testimonial_2_name: 'Ali Asaf Küçük',
  testimonial_2_role: 'Business Owner',
  testimonial_2_company: 'Logistics - 55 Employees',
  testimonial_3_text: 'As a fast-growing startup, UpOne’s recruitment assistant saved us a lot of time by automatically screening CVs. The AI-generated interview questions are highly effective.',
  testimonial_3_name: 'Osman Tarık Özer',
  testimonial_3_role: 'Co-Founder',
  testimonial_3_company: 'Startup - 25 Employees',

  industries_title: 'Industries We Serve',
  industry_1_title: 'Manufacturing & Industrial',
  industry_1_desc: 'Shift tracking and workforce management',
  industry_2_title: 'Hospitality & Tourism',
  industry_2_desc: 'Seasonal staff and multi-location operations',
  industry_3_title: 'Startups & Technology',
  industry_3_desc: 'Fast growth and flexible working models',

  faq_title: 'Frequently Asked Questions',
  faq_1_q: 'How long does setup take?',
  faq_1_a: 'Setup takes only 5 minutes. Upload your employee data in Excel format, integrate your Telegram bot, and let your employees register. You can receive your first report within an hour.',
  faq_2_q: 'Why do you use Telegram?',
  faq_2_a: 'Telegram is secure, fast, and already familiar to most employees. No need to download an extra app — all actions can be done through the bot. Location sharing is also very simple.',
  faq_3_q: 'How do you ensure data security?',
  faq_3_a: 'All data is stored in encrypted form. We use Telegram’s end-to-end encryption infrastructure. Your data is backed up, GDPR/KVKK compliant, and never shared with third parties.',
  faq_4_q: 'Do you offer a free trial?',
  faq_4_a: 'We currently do not offer a free trial, but you can request a free demo call via WhatsApp, where we walk you through the full system in detail.',
  faq_5_q: 'Can it integrate with my existing systems?',
  faq_5_a: 'Yes, UpOne provides flexible integration options. It can connect with payroll systems, ERP software, and other HR tools. Contact us for custom integrations.',
  faq_6_q: 'What kind of reports are provided?',
  faq_6_a: 'You can generate daily/monthly attendance reports, lateness analyses, leave usage reports, department-based reports, payroll summaries, and custom reports.',
  faq_7_q: 'Do you have a mobile app?',
  faq_7_a: 'Since Telegram is already a mobile app, we didn’t build a separate one. Employees perform all operations through Telegram, while managers have access to a web dashboard.',
  faq_8_q: 'What is your cancellation policy?',
  faq_8_a: 'You can cancel your subscription anytime. Your data will be stored for 30 days and can be provided upon request. There is no automatic renewal.',

  cta_title: 'Automate Your HR Processes Today and Start Saving',
  cta_subtitle: 'Setup takes 5 minutes, first report within 1 hour',
  cta_whatsapp: 'Start Now via WhatsApp',
  cta_secondary: 'View Pricing',

  footer_about: 'UpOne is an AI-powered HR automation platform. Manage attendance, leave requests, and recruitment processes automatically through Telegram.',
  footer_product: 'Product',
  footer_company: 'Company',
  footer_support: 'Support',
  footer_contact: 'Contact',
  footer_features: 'Features',
  footer_pricing: 'Pricing',
  footer_how: 'How It Works',
  footer_demo: 'Request Demo',
  footer_about_us: 'About Us',
  footer_contact_us: 'Contact Us',
  footer_blog: 'Blog',
  footer_careers: 'Careers',
  footer_help: 'Help Center',
  footer_whatsapp: 'WhatsApp Support',
  footer_docs: 'Documentation',
  footer_faq: 'FAQ',
  footer_phone: '+90 543 603 71 90',
  footer_email: 'info@upone.ai',
  footer_address: 'Konya, Turkey',
  footer_rights: '© 2024 UpOne. All rights reserved.',
  footer_privacy: 'Privacy Policy',
  footer_terms: 'Terms of Use',
  footer_cookies: 'Cookie Policy',

  references_title: 'Our References',
  references_subtitle: 'Leading companies in Turkey trust UpOne',

  success_stories_title: 'Success Stories',
  success_stories_subtitle: 'Discover how our clients achieved success with UpOne',
  success_stories_empty: 'No success stories added yet.',

  about_title: 'About Us',
  about_subtitle: 'UpOne: The AI Revolution in Human Resources Management',
  about_section_1_title: 'Our Mission',
  about_section_1_text: 'At UpOne, we aim to automate HR processes through artificial intelligence, increasing efficiency and enabling human-centered management. Our AI assistant, running on Telegram, offers a simple 5-minute setup and effortless usability.',
  about_section_2_title: 'Our Vision',
  about_section_2_text: 'To be a modern and intelligent HR management platform accessible to businesses of all sizes in Turkey. We want to free HR departments from manual work and empower them to make strategic decisions.',
  about_section_3_title: 'Our Values',
  about_section_3_text: 'Innovation, transparency, customer satisfaction, and continuous improvement lie at the heart of what we do. We work every day to provide a better product, listen to our clients, and stay ahead of technology trends.',
  about_team_title: 'Our Team',
  about_team_text: 'The UpOne team consists of experts in artificial intelligence, software development, and human resources. We are passionate about delivering the best experience to our customers.',

  why_us_title: 'Why UpOne?',
  why_us_subtitle: 'Discover what sets us apart from the competition',
  why_us_reason_1_title: '5-Minute Setup',
  why_us_reason_1_desc: 'No complex installation required. Upload your JSON file, integrate your bot, and start using immediately.',
  why_us_reason_2_title: 'Telegram-Based',
  why_us_reason_2_desc: 'Employees perform all actions directly through Telegram — no need to learn a new app.',
  why_us_reason_3_title: '100% Automated',
  why_us_reason_3_desc: 'Our AI assistant handles attendance tracking, leave approvals, and reporting — no manual effort needed.',
  why_us_reason_4_title: 'AI-Powered',
  why_us_reason_4_desc: 'With natural language processing, employees easily make requests while AI takes smart actions.',
  why_us_reason_5_title: 'Affordable',
  why_us_reason_5_desc: 'We offer a modern HR solution for every budget — no huge investments required.',
  why_us_reason_6_title: '24/7 Support',
  why_us_reason_6_desc: 'Our support team is always available via WhatsApp to answer your questions instantly.',
}

};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.tr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
